//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.28 at 10:06:48 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/mbrindam/samples/webservices/accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mbrindam.samples.webservices.accountservice;
